[project]
name = "nexhacks-longbench"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "setuptools>=80.9.0",
    "transformers==4.45.0",
    "vllm==0.5.3.post1",
    "wheel>=0.45.1",
]
